# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_cumsum <- function(u, next_x, t) {
    .Call('_tpcaMonitoring_update_cumsum', PACKAGE = 'tpcaMonitoring', u, next_x, t)
}

update_cumsum2 <- function(v, u, next_x, m, t) {
    .Call('_tpcaMonitoring_update_cumsum2', PACKAGE = 'tpcaMonitoring', v, u, next_x, m, t)
}

update_sumsC <- function(sums, next_x, m, t) {
    .Call('_tpcaMonitoring_update_sumsC', PACKAGE = 'tpcaMonitoring', sums, next_x, m, t)
}

log_lik_ratio <- function(m, t, k, s_full, s_pre, s_post) {
    .Call('_tpcaMonitoring_log_lik_ratio', PACKAGE = 'tpcaMonitoring', m, t, k, s_full, s_pre, s_post)
}

log_liks_matC <- function(sums, m, t, w, p0) {
    .Call('_tpcaMonitoring_log_liks_matC', PACKAGE = 'tpcaMonitoring', sums, m, t, w, p0)
}

